version: '3.8'

services:
  php:
    image: php:7.4-fpm
    container_name: php-container
    volumes:
      - ./src:/var/www/html
    networks:
      - web

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - web

networks:
  web:
    driver: bridge
