version: '3.8'

services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./app:/var/www/html
    # Для работы сессий
    command: sh -c "mkdir -p /var/lib/php/sessions && chmod -R 777 /var/lib/php/sessions && php-fpm"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php