version: '3.8'

services:
  php:
    image: php:8.1-fpm
    container_name: php_fpm
    volumes:
      - ./src:/var/www/html

  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
